### PR TITLE
[HYDRATOR-1025] Fixed issues related to parsing xml reserved characters in the xml data for XMLReader plugin

### PR DESCRIPTION
**Pull request by romy-khetan**

### CODE REVIEW

**Comment by russorat** [comment]
still having issues validating this is working in hydrator. @romy-khetan is currently investigating.

**Comment by russorat** [comment]
Changes LGTM

**Comment by abhinavbansal246** [comment]
@romy-khetan Please paste the last 20 lines of successful ITN run against the new code.
Please confirm that this has been tested on a cluster

**Comment by romy-khetan** [comment]
@abhinavbansal246 Currently, due to FileSet issues in XMLReader plugins, tests including ITN tests has been ignored until the issue is resolved. Although verified the fix through creating pipeline in the cluster using UI.

**Comment by abhinavbansal246** [comment]
http://builds.cask.co/browse/HYP-BAD162/

**Pull request merged**
