### PR TITLE
Append the filename to the location representing the partition for writing data.

### PR DESCRIPTION
**Pull request by sagarkapare**

### CODE REVIEW

**Comment by sagarkapare** [comment]
Few more test cases failed http://builds.cask.co/browse/HYP-DBT-148 because of the removal of `ScriptTransform`. Fixed them in the second commit.

**Comment by sagarkapare** [comment]
New build is running here - http://builds.cask.co/browse/HYP-DBT42-2

**Comment by sagarkapare** [comment]
Build is green http://builds.cask.co/browse/HYP-DBT42-2

**Comment by albertshau** [comment]
lgtm

**Pull request merged**
