### PR TITLE
Revert "Merge release/1.3 to develop"

### PR DESCRIPTION
**Pull request by rohitsinha54**
Reverts caskdata/hydrator-plugins#260

Reverting this since it looks like the merge to develop from release/1.3 was not done properly as it missed a commit from here: https://github.com/caskdata/hydrator-plugins/pull/257 due which ITN is failed on develop. 

I will open another PR to merge release to develop as soon as this is merged.

### CODE REVIEW

**Comment by anwar6953** [comment]
that commit was missed because Vinisha's local release/1.3 branch probably wasn't up to date.
So, when she branched off it, it didn't have recent commits.

So, instead of reverting her PR, just merge release/1.3 to develop once more - and it will have the commits that she missed. (She would've seen these commits if she did git pull).

**Comment by sagarkapare** [comment]
LGTM

**Comment by anwar6953** [comment]
No; don't merge this; see above comment.

edit: technically, you could do this revert and do the entire merge over, but its cleaner (history) just to merge what's ahead on the release branch.

**Comment by rohitsinha54** [comment]
I don't think it really matter as how it is done. Both will produce the same result and moreover reverting and merging will keep develop more cleaner I think. But if you want the other way thats fine too. I will open PR for that.

**Comment by rohitsinha54** [comment]
PR from earlier discussion: https://github.com/caskdata/hydrator-plugins/pull/262

**Pull request closed without merging**
