### PR TITLE
(CDAP-4849) Use password widget for password field in teradata source

### PR DESCRIPTION
**Pull request by bdmogal**

### CODE REVIEW

**Comment by anwar6953** [comment]
lgtm

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by gokulavasan** [comment]
What about batch-sink?

**Comment by bdmogal** [comment]
it was only missing in `Teradata-batchsource`. We don't have a `Teradata-batchsink`. Checked that `Database-batchsource` and `Database-batchsink` use password.

**Comment by gokulavasan** [comment]
@bdmogal Oh ok right. Thanks!

**Pull request merged**
