### PR TITLE
copying cdap-etl-lib from cdap to here as core-plugins

### PR DESCRIPTION
**Pull request by albertshau**
Also doing some pom cleanup to remove cdap-etl-lib and replace
with core-plugins.

### CODE REVIEW

**Comment by gsps1** [comment]
using gitk for code review, as github is not able to render everything due to a lot of changes. so just adding comments here.

**Comment by gsps1** [comment]
logback.xml in core-plugins still uses co.cask.cdap class names for appender and logger names.

**Comment by albertshau** [comment]
good catch on logback, corrected the class names

**Comment by gsps1** [comment]
one minor comments, LGTM otherwise

**Pull request merged**
