### PR TITLE
CDAP-18359 get error message from root cause

### PR DESCRIPTION
**Pull request by seanzhougoogle**

### CODE REVIEW

**Review by tivv — COMMENTED** [review]
Could you please remove unrelated changes? Also, it would be great to have at least some tests for various databases we directly support. E.g. take some invalid host name and see what message do we get this way. For postgresql it should be better than now, but we'd better check others as well

**Comment by seanzhougoogle** [comment]
> Could you please remove unrelated changes? 

sorry, didn't notice that I committed the submodule reference


>Also, it would be great to have at least some tests for various databases we directly support. E.g. take some invalid host name and see what message do we get this way. For postgresql it should be better than now, but we'd better check others as well

Good point :) Tested with mysql, oracle, sql server, with wrong connection info, error messages got make sense:)

**Comment by tivv** [comment]
Is it easy enough to have those tests automated?

**Comment by seanzhougoogle** [comment]
> Is it easy enough to have those tests automated?


not yet, those require some real database to be brought up when the test case starts. We have plan to improve it by bring up some docker images.

**Review by tivv — APPROVED** [review]

**Pull request merged**
