### PR TITLE
CDAP-12731 Fix HBase sink classloader issue, that fails for Spark execution engine

### PR DESCRIPTION
**Pull request by anwar6953**
[CDAP-12731](https://issues.cask.co/browse/CDAP-12731) Fix HBase sink classloader issue, that fails for Spark execution engine.

https://builds.cask.co/browse/HYP-BAD372-5

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM

**Comment by anwar6953** [comment]
On-hold, because this change causes a regression in the hbase source.

**Comment by anwar6953** [comment]
Fixed the hbase source, and tested w/ spark + MR.

**Comment by anwar6953** [comment]
And now the unit tests are failing due to the classloading changes (but on cluster, it works)...

**Comment by chtyim** [comment]
LGTM

**Comment by anwar6953** [comment]
Fixed the test cases. Build is green. Squashing and merging.

**Pull request merged**
