### PR TITLE
(CDAP-11410) Added a SparkCompute plugin that do arbitrary Scala code execution

### PR DESCRIPTION
**Pull request by chtyim**
Still missing the example in the doc. @sreevatsanraman @albertshau Any suggestion on good example?

### CODE REVIEW

**Comment by chtyim** [comment]
This depends on https://github.com/caskdata/cdap/pull/9033

**Comment by chtyim** [comment]
Also verified on cluster is working.

**Review by sreevatsanraman — COMMENTED** [review]
LGTM

**Comment by chtyim** [comment]
Build passed https://builds.cask.co/browse/HYP-BAD312

**Pull request merged**
