### PR TITLE
Update version 1.3.0-SNAPSHOT --> 1.3.0

### PR DESCRIPTION
**Pull request by anwar6953**
Simply ran:
`mvn versions:set -DnewVersion=1.3.0 -DgenerateBackupPoms=false`

Similar to https://github.com/caskdata/hydrator-plugins/pull/158

Compilation passed locally:
`mvn clean package -DskipTests`

### CODE REVIEW

**Comment by sagarkapare** [comment]
LGTM

**Comment by anwar6953** [comment]
We should merge this as the last PR for 3.4.0.
So not merging until we need to.

**Comment by sreevatsanraman** [comment]
CDAP version should bechanged to 3.4.0

**Comment by sreevatsanraman** [comment]
Fixed.

**Pull request merged**
