### PR TITLE
Fixing the directory structure for solr search plugins

### PR DESCRIPTION
**Pull request by abhinavbansal246**

### CODE REVIEW

**Comment by abhinavbansal246** [comment]
https://issues.cask.co/browse/HYDRATOR-1033

**Review by bdmogal — APPROVED** [review]
LGTM

**Comment by abhinavbansal246** [comment]
earlier failed build
http://builds.cask.co/browse/CDAP-BUT-BMA-628/log

**Comment by abhinavbansal246** [comment]
## last few lines of local build

Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/co/cask/hydrator/plugin/common/class-use/SolrRecordWriter.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/co/cask/hydrator/plugin/common/class-use/SolrOutputFormat.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/co/cask/hydrator/plugin/realtime/class-use/RealtimeSolrSearchSink.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/co/cask/hydrator/plugin/batch/package-use.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/co/cask/hydrator/plugin/common/package-use.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/co/cask/hydrator/plugin/realtime/package-use.html...
Building index for all the packages and classes...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/overview-tree.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/index-all.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/deprecated-list.html...
Building index for all classes...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/allclasses-frame.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/allclasses-noframe.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/index.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/overview-summary.html...
Generating /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/target/site/apidocs/help-doc.html...
3 warnings
[WARNING] Javadoc Warnings
[WARNING] /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/src/main/java/co/cask/hydrator/plugin/common/SolrSearchSinkConfig.java:105: warning: no description for @return
[WARNING] \* @return
[WARNING] ^
[WARNING] /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/src/main/java/co/cask/hydrator/plugin/common/SolrSearchSinkConfig.java:179: warning: no description for @param
[WARNING] \* @param inputSchema
[WARNING] ^
[WARNING] /Users/Abhinav/repos/hydrator-plugins/solrsearch-plugins/src/main/java/co/cask/hydrator/plugin/common/SolrSearchSinkConfig.java:191: warning: no description for @param
[WARNING] \* @param inputSchema
[WARNING] ^
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.928 s
[INFO] Finished at: 2016-10-25T19:24:14-07:00
[INFO] Final Memory: 86M/1450M
[INFO] ------------------------------------------------------------------------

**Pull request merged**
