### PR TITLE
fixing deps for SQS plugin

### PR DESCRIPTION
**Pull request by russorat**
fix for https://issues.cask.co/browse/CDAP-6318

### CODE REVIEW

**Comment by awholegunch** [comment]
This isn't in this PR, but at the bottom of that file, there is:

```
            <_exportcontents>
              co.cask.hydrator.plugin.batch.*;
              co.cask.hydrator.plugin.transform.*;
              co.cask.hydrator.plugin.validator.*;
              co.cask.hydrator.plugin.common;
              org.apache.avro.mapreduce;
              co.cask.hydrator.plugin.realtime.*;
              co.cask.hydrator.plugin.transform.*;
              co.cask.hydrator.plugin.validator.*;
              co.cask.hydrator.plugin.common;
              parquet.avro.*;
            </_exportcontents>
```

Any reason why some of those entries are duplicated?

```
 co.cask.hydrator.plugin.transform.*;
              co.cask.hydrator.plugin.validator.*;
              co.cask.hydrator.plugin.common;
```

appears twice...

**Comment by chtyim** [comment]
LGTM

**Comment by sreevatsanraman** [comment]
@jj @russorat no reason to have duplicate entries. Can be removed.

**Comment by russorat** [comment]
thanks @sreevatsanraman will close this and open a new PR for removing those. FYI @awholegunch

**Pull request merged**
