### PR TITLE
Remove snapshot (for release 1.3.1)

### PR DESCRIPTION
**Pull request by anwar6953**
Note - this will not work until cdap 3.4.1 is released (or locally installed).

### CODE REVIEW

**Comment by anwar6953** [comment]
Note: depends on https://github.com/caskdata/cdap/pull/5765

**Comment by rohitsinha54** [comment]
LGTM

**Comment by wolf31o2** [comment]
👍 LGTM

**Comment by sreevatsanraman** [comment]
LGTM

**Pull request merged**
