### PR TITLE
HYDRATOR-1160 fix failing orc test

### PR DESCRIPTION
**Pull request by albertshau**

### CODE REVIEW

**Comment by anwar6953** [comment]
The plugin has the necessary dependency otherwise defined in the pom file, so that it has access to the classes in distributed/SDK?

If so, LGTM.

Edit: I guess the change which caused this change to be needed (https://issues.cask.co/browse/CDAP-7256) shouldn't have affected distributed, and in order to work there, the necessary dependencies must already have been defined.

**Comment by albertshau** [comment]
I'll test that part out next, but I don't see how it would have worked before if it didn't, since that class wouldn't have been accessible before either I think...

**Comment by anwar6953** [comment]
Right, appended an edit to my original comment.

**Comment by albertshau** [comment]
cool, will double check before merging

**Comment by albertshau** [comment]
http://builds.cask.co/browse/HYP-BAD188

**Comment by albertshau** [comment]
verified it still works on sdk and on cluster.

**Pull request merged**
