### PR TITLE
Enabled macros for spark plugins

### PR DESCRIPTION
**Pull request by knazir**
Fields that have been macro enabled:

`NaiveBayesTrainer`:
- fileSetName
- path
- numFeatures

`NaiveBayesClassifier`:
- fileSetName
- path
- numFeatures

`KafkaStreamingSource`:
- brokers
- topics

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
How will the users know that a field is macro enabled? The descriptions in the docs should reflect this.

**Comment by knazir** [comment]
Guild is breen: http://builds.cask.co/browse/HYP-BAD49-2

**Comment by knazir** [comment]
Guild is breen: http://builds.cask.co/browse/HYP-BAD49-3

**Comment by albertshau** [comment]
lgtm

**Pull request merged**
