### PR TITLE
[HYDRATOR-1066] - Removing Decision tree path for destination fileset

### PR DESCRIPTION
**Pull request by ananya-bhattacharya**
Fix for https://issues.cask.co/browse/HYDRATOR-1066
Removing config parameter path for destination fileset.

### CODE REVIEW

**Comment by abhinavbansal246** [comment]
Even if the config path is being inherited, it should still show up in the configuration as well as the ui wizard, However it should be optional (@nullable). Where are the base classes getting the path from? Are we assuming default path in every case?

**Comment by ananya-bhattacharya** [comment]
We are not assuming default path for any case.
However, we are appending the `path` to the fileset location only if it is not null or not empty.

Please let me know if this is okay.

**Comment by abhinavbansal246** [comment]
LGTM
Please squash commits

**Comment by shashankmoghe** [comment]
Ran the ITN 

[INFO] --- maven-bundle-plugin:2.5.4:bundle (default) @ spark-plugins ---
[WARNING] Bundle co.cask.hydrator:spark-plugins:jar:1.5.0-SNAPSHOT : Unused Export-Package instructions: [org.apache.spark.streaming.scheduler.*]
[WARNING] Bundle co.cask.hydrator:spark-plugins:jar:1.5.0-SNAPSHOT : Export co.cask.hydrator.plugin.spark,  has 5,  private references [javax.annotation, co.cask.cdap.api.data.sch
ema, co.cask.cdap.api.annotation, co.cask.cdap.api.data.format, co.cask.hydrator.common],
[WARNING] Bundle co.cask.hydrator:spark-plugins:jar:1.5.0-SNAPSHOT : Export org.apache.spark.streaming.kafka,  has 15,  private references [scala.collection.immutable, scala.colle
ction.mutable, org.slf4j, scala, org.I0Itec.zkclient, kafka.message, scala.collection, kafka.consumer, scala.util, scala.runtime, kafka.server, kafka.cluster, kafka.producer, scal
a.reflect, kafka.api],
[WARNING] Bundle co.cask.hydrator:spark-plugins:jar:1.5.0-SNAPSHOT : Export kafka.common,  has 10,  private references [scala.collection.immutable, com.yammer.metrics.core, scala.
runtime, kafka.cluster, scala, kafka.metrics, kafka.utils, org.apache.log4j, scala.collection, scala.reflect],
[WARNING] Bundle co.cask.hydrator:spark-plugins:jar:1.5.0-SNAPSHOT : Export kafka.serializer,  has 2,  private references [kafka.utils, scala.reflect],
[WARNING] Bundle co.cask.hydrator:spark-plugins:jar:1.5.0-SNAPSHOT : Export org.apache.spark.streaming.twitter,  has 5,  private references [org.slf4j, scala.runtime, scala, scala
.collection, scala.reflect],
[WARNING] Bundle co.cask.hydrator:spark-plugins:jar:1.5.0-SNAPSHOT : Export co.cask.hydrator.common.http,  has 3,  private references [co.cask.cdap.api.data.schema, co.cask.cdap.a
pi.annotation, co.cask.cdap.api.data.format],
[WARNING] Bundle co.cask.hydrator:spark-plugins:jar:1.5.0-SNAPSHOT : Invalid package name: 'org.spark-project.guava.base'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:20.329s
[INFO] Finished at: Tue Nov 22 12:56:20 IST 2016
[INFO] Final Memory: 78M/567M
[INFO] ------------------------------------------------------------------------

**Comment by abhinavbansal246** [comment]
Please use rebase instead of merge, Do rebase and squash in a single step and Use better commit messages than "squashing the commits"

**Pull request merged**
