### PR TITLE
[HYDRATOR-1096] Fix for table sink dataset name macro substitution

### PR DESCRIPTION
**Pull request by shashankmoghe**
https://issues.cask.co/browse/HYDRATOR-1096

### CODE REVIEW

**Comment by russorat** [comment]
@shashankmoghe please add a unit test

**Comment by shashankmoghe** [comment]
@russorat Added unit test to verify fix for table dataset name macro substitution exception

**Comment by russorat** [comment]
LGTM

**Comment by shashankmoghe** [comment]
ITN result:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] integration-test .................................. SUCCESS [6:33.298s]
[INFO] integration-test-core ............................. SUCCESS [12.115s]
[INFO] integration-test-remote ........................... SUCCESS [16:47.445s]
[INFO] integration-test-standalone ....................... SUCCESS [3.562s]
[INFO] upgrade-test ...................................... SUCCESS [2.535s]
[INFO] long-running-test ................................. SUCCESS [3.102s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23:42.441s
[INFO] Finished at: Fri Jan 06 14:30:26 IST 2017
[INFO] Final Memory: 84M/318M
[INFO] ------------------------------------------------------------------------

**Pull request merged**
