### PR TITLE
Table Sink : Row key inclusion in output schema is optional now

### PR DESCRIPTION
**Pull request by nitinmotgi**
Before it was mandatory to have row key in the output schema. This change makes it optional.

### CODE REVIEW

**Comment by nitinmotgi** [comment]
PR https://github.com/caskdata/hydrator-plugins/pull/270 has to be merged for this to look clean.

**Comment by anwar6953** [comment]
#270 is merged, but it still difficult to review this.
Could you try to merge develop into this branch and then push again? That might clean it up. Currently, all the changes of #270 are still visible.
Maybe simply reopening the PR will clean it up also.

**Comment by nitinmotgi** [comment]
@anwar6953 fixed it -- can you please review.

**Comment by anwar6953** [comment]
LGTM

**Pull request merged**
