### PR TITLE
Remove kafka source

### PR DESCRIPTION
**Pull request by CuriousVini**
Because we have added kafka plugins in [hydrator org](https://github.com/hydrator/kafka-plugins), we are removing Kafka Source. 

Compilation succeeded locally. 

Build: https://builds.cask.co/browse/HYP-BAD265-5

### CODE REVIEW

**Review by albertshau — COMMENTED** [review]
can you remove the kafka streaming dependency and exports from the pom

**Comment by CuriousVini** [comment]
@albertshau Addressed comments. Please take another look

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by CuriousVini** [comment]
Build is green. Merging

**Pull request merged**
