### PR TITLE
CDAP-13924: Make plugins which requires transactions specify it throu…

### PR DESCRIPTION
**Pull request by rohitsinha54**
…gh Requirements annotation

### Summary
- For [Issue 13924] we introduced an annotation `Requirement` which can be used by plugins to specify  its requirements. 
- In this PR we are marking some of the known plugins with their requirements.

### CODE REVIEW

**Review by albertshau — COMMENTED** [review]
can you also annotate the snapshot plugins (they use partitioned file set)

**Comment by rohitsinha54** [comment]
@albertshau : Thanks. Done. Please have another look.

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by rohitsinha54** [comment]
Waiting for a successful BUT to publish new api to run hydrator tests
https://builds.cask.co/browse/CDAP-BUT-1433

**Comment by rohitsinha54** [comment]
Hydrator Build: https://builds.cask.co/browse/HYP-BAD448-7

**Pull request merged**
