### PR TITLE
Fix develop build failure by creating a common test base for transfor…

### PR DESCRIPTION
**Pull request by gokulavasan**
…m module and add all the plugins used to the plugin artifact

### CODE REVIEW

**Comment by gokulavasan** [comment]
https://issues.cask.co/browse/CDAP-6162 is blocking this PR.

**Comment by gokulavasan** [comment]
@sreevatsanraman Please review. Thanks!

**Comment by anwar6953** [comment]
Can you explain how having a common test base for transform plugin tests - how this fixes the build failure?
Seems only one class is utilizing the new common test base anyways.

**Comment by sreevatsanraman** [comment]
LGTM

**Pull request merged**
