### PR TITLE
Merge release 1.6 to develop

### PR DESCRIPTION
**Pull request by Nishith**
Conflicts in kafka source, which was removed and in poms.

### CODE REVIEW

**Comment by awholegunch** [comment]
Docs LGTM

**Comment by CuriousVini** [comment]
I dont see any `spark-plugins/pom.xml` changes

**Comment by Nishith** [comment]
Because I picked the Develop version.

**Comment by CuriousVini** [comment]
I do not see changes from https://github.com/caskdata/hydrator-plugins/pull/628/commits/fb184cfe5725cc31bb3d37938c7219f3ab051d73 commit

**Pull request closed without merging**
